### ISSUE TITLE
using bms type tdt generates traceback and fails to connect

### ISSUE THREAD

**Issue by TheKorn2** [fl4p/batmon-ha#330]
Configuring bms type tdt generates a traceback. 

* Include exact BMS model name  -- unable to retrieve
* 
* Query HW and SW numbers from the BMS app  -- SW WT30_10004SW13_L_02   HW unknown
* 
* Enable verbose_log

```
Paste log output between BEGIN and END:
BEGIN 

(too long to paste into a ticket, attached as a text file instead)

[tdt_startup_log.txt](https://github.com/user-attachments/files/23062340/tdt_startup_log.txt)

[tdt_startup_log.txt](https://github.com/user-attachments/files/23062341/tdt_startup_log.txt)

```

Using bluetoothctl, the bt controller can see the BMS, but for some reason batmon-ha won't connect:

```
[bluetooth]# power off
Changing power off succeeded
[CHG] Controller 8C:68:8B:E2:0E:22 Powered: no
[CHG] Controller 8C:68:8B:E2:0E:22 Discovering: no
[CHG] Controller 8C:68:8B:E2:0E:22 Class: 0x00000000
[bluetooth]# power on
[CHG] Controller 8C:68:8B:E2:0E:22 Class: 0x006c0104
Changing power on succeeded
[CHG] Controller 8C:68:8B:E2:0E:22 Powered: yes
[bluetooth]# scan on
Discovery started
[CHG] Controller 8C:68:8B:E2:0E:22 Discovering: yes
[NEW] Device 0C:43:14:93:02:2F ResMed 015537
[NEW] Device 20:ED:BD:21:09:EE 20-ED-BD-21-09-EE
[NEW] Device 0D:8F:D8:06:A8:B8 0D-8F-D8-06-A8-B8
[NEW] Device 58:3E:A7:4C:72:1C 58-3E-A7-4C-72-1C
[NEW] Device C0:D6:3C:58:27:87 WTaEaAA25342355   <-- there it is!
[NEW] Device 1F:E1:89:2B:90:BE 1F-E1-89-2B-90-BE
[bluetooth]# scan off
Discovery stopped
[CHG] Device 1F:E1:89:2B:90:BE RSSI is nil
[CHG] Device C0:D6:3C:58:27:87 RSSI is nil
[CHG] Device 58:3E:A7:4C:72:1C RSSI is nil
[CHG] Device 0D:8F:D8:06:A8:B8 RSSI is nil
[CHG] Device 20:ED:BD:21:09:EE RSSI is nil
[CHG] Device 0C:43:14:93:02:2F TxPower is nil
[CHG] Device 0C:43:14:93:02:2F RSSI is nil
[CHG] Controller 8C:68:8B:E2:0E:22 Discovering: no
```

Happy to grab anything else you'd like, just say the word!

**Comment by fl4p** [comment]
Your log files have vanished.
Maybe disable verbose log and post it again

**Comment by fl4p** [comment]
Update to 1.92 should fix it. If not, please re-open

**Comment by TheKorn2** [comment]
Cannot re-open issue, github says I don't have permissions.

Upgrading to 1.92 did not fix issue. Trying to start up says bluez operation in progress.

Where are logs stored when installed standalone?  Can't seem to find where they exist.

**Comment by TheKorn2** [comment]
Looks like the root of this is one hell of a bluetooth/bluez cluster in ubuntu, so probably not really your problem.

Still want to know where the logs for standalone exist.  (Might want to add to the standalone doc.)

**Comment by fl4p** [comment]
> Still want to know where the logs for standalone exist. (Might want to add to the standalone doc.)

there are no log files, everything is printed out on the console

**Comment by TheKorn2** [comment]
OK, had some time (yay Christmas!) to dig into this.  

Right now, the status is that the bluetooth controller can see all my batteries, and they're ringing in pretty strongly:

```
[bluetooth]# Agent registered
[bluetooth]# [CHG] Controller 8C:68:8B:E2:0E:22 Pairable: yes
[bluetooth]# scan le
[bluetooth]# SetDiscoveryFilter failed: org.bluez.Error.NotReady
[bluetooth]# Failed to start discovery: org.bluez.Error.NotReady
[bluetooth]# power off
[bluetooth]# Changing power off succeeded
[bluetooth]# power on
[bluetooth]# Failed to set power on: org.bluez.Error.Failed
[bluetooth]# power on
[bluetooth]# hci0 class of device changed: 0x6c0104
[bluetooth]# [CHG] Controller 8C:68:8B:E2:0E:22 Class: 0x006c0104 (7078148)
[bluetooth]# hci0 new_settings: powered bondable ssp br/edr le secure-conn
[bluetooth]# Changing power on succeeded
[bluetooth]# [CHG] Controller 8C:68:8B:E2:0E:22 Powered: yes
[bluetooth]# scan le
[bluetooth]# SetDiscoveryFilter success
[bluetooth]# Discovery started
[bluetooth]# [CHG] Controller 8C:68:8B:E2:0E:22 Discovering: yes
[bluetooth]# [NEW] Device 0C:43:14:93:02:2F ResMed 015537
[bluetooth]# [NEW] Device 07:EE:3C:36:78:F6 07-EE-3C-36-78-F6
[bluetooth]# [NEW] Device C0:D6:3C:58:27:87 WTaEaAA25342355
[bluetooth]# [NEW] Device 2C:53:AF:7D:E8:EB 2C-53-AF-7D-E8-EB
[bluetooth]# [NEW] Device 26:94:56:79:F4:6F 26-94-56-79-F4-6F
[bluetooth]# [NEW] Device C0:D6:3C:58:17:76 WTaEaAA25341133
[bluetooth]# [NEW] Device 33:96:C3:65:9F:6A 33-96-C3-65-9F-6A
[bluetooth]# [NEW] Device 4F:41:23:D0:8F:BA 4F-41-23-D0-8F-BA
[bluetooth]# [NEW] Device C8:9C:FD:AD:AF:DE C8-9C-FD-AD-AF-DE
[bluetooth]# [NEW] Device C0:D6:3C:58:2A:B3 WTaEaAA25344733
[bluetooth]# [NEW] Device C0:D6:3C:58:2A:B3 WTaEaAA25344733
[bluetooth]# [NEW] Device C0:D6:3C:59:04:03 WTaEaAA25342774
[bluetooth]# [NEW] Device C1:6C:B5:F5:50:FB C1-6C-B5-F5-50-FB
[bluetooth]# [NEW] Device E8:88:6C:3F:F6:4C E50000253344939356﻿​
[bluetooth]# [CHG] Device 0C:43:14:93:02:2F RSSI: 0xffffffac (-84)
[bluetooth]# [CHG] Device 26:94:56:79:F4:6F RSSI: 0xffffffbc (-68)
[bluetooth]# [CHG] Device 07:EE:3C:36:78:F6 RSSI: 0xffffffb2 (-78)
[bluetooth]# [CHG] Device C0:D6:3C:59:04:03 RSSI: 0xffffffa2 (-94)
[bluetooth]# [CHG] Device 2C:53:AF:7D:E8:EB RSSI: 0xffffffb2 (-78)
[bluetooth]# [CHG] Device 4F:41:23:D0:8F:BA RSSI: 0xffffffac (-84)
[bluetooth]# [CHG] Device 4F:41:23:D0:8F:BA ManufacturerData.Key: 0x0075 (117)
[bluetooth]# [CHG] Device 4F:41:23:D0:8F:BA ManufacturerData.Value:
[bluetooth]#   bc 4f df 24 16 a1 d8                             .O.$...
[bluetooth]# [CHG] Device 0C:43:14:93:02:2F RSSI: 0xffffffaa (-86)
[bluetooth]# [CHG] Device C0:D6:3C:58:2A:B3 RSSI: 0xffffffa6 (-90)
[bluetooth]# [CHG] Device C0:D6:3C:58:27:87 RSSI: 0xffffffb0 (-80)
[bluetooth]# [CHG] Device 33:96:C3:65:9F:6A RSSI: 0xffffffb4 (-76)
[bluetooth]# [CHG] Device C0:D6:3C:58:17:76 RSSI: 0xffffffb0 (-80)
[bluetooth]# [CHG] Device E8:88:6C:3F:F6:4C RSSI: 0xffffffb2 (-78)
[bluetooth]# [CHG] Device 0C:43:14:93:02:2F RSSI: 0xffffffaa (-86)
[bluetooth]# [NEW] Device 66:DF:10:C6:E5:A0 66-DF-10-C6-E5-A0
[bluetooth]# [CHG] Device 0C:43:14:93:02:2F RSSI: 0xffffffaa (-86)
[bluetooth]# [CHG] Device 66:DF:10:C6:E5:A0 RSSI: 0xffffffa0 (-96)
[bluetooth]# [CHG] Device 0C:43:14:93:02:2F RSSI: 0xffffffae (-82)
[bluetooth]# [CHG] Device C0:D6:3C:59:04:03 RSSI: 0xffffffa8 (-88)
[bluetooth]# [CHG] Device 2C:53:AF:7D:E8:EB RSSI: 0xffffffc4 (-60)
[bluetooth]# [CHG] Device 4F:41:23:D0:8F:BA RSSI: 0xffffffaa (-86)
[bluetooth]# [CHG] Device 4F:41:23:D0:8F:BA ManufacturerData.Key: 0x0075 (117)
```

(rest truncated, can provide if it'd be helpful)

But even though I can see it with bluetoothctl , batmon-ha can't connect to it (this also shows the traceback that originally caused me to open this):

```
13:50:15 WARNING [store] error reading /data/options.json, trying options.json [Errno 2] No such file or directory: '/da
ta/options.json'
13:50:15 INFO [bt] BT Discovery (5 seconds):
13:50:20 INFO [bt]  - no devices found -
13:50:20 INFO [main] Verbose logging enabled
13:50:20 INFO [main] Batmon ver 1.92, aiobmsble ver 0.13.0, Bleak ver 1.1.1, BtBackend ver bluez-v5.72
13:50:20 INFO [__init__] Verbose log for C0:D6:3C:58:27:87 enabled
13:50:20 INFO [main] connecting mqtt (REDACTED)
13:50:20 INFO [main] Fetching 1 BMS + 0 virtual + 0 others serially, period=5.00s, keep_alive=True
13:50:20 ERROR [sampling] battery1 error (#1): [org.bluez.Error.InProgress] Operation already in progress
Traceback (most recent call last):
  File "/home/vince/batmon-ha2/bmslib/sampling.py", line 155, in __call__
    s = await self._sample_inner()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vince/batmon-ha2/bmslib/sampling.py", line 231, in _sample_inner
    async with bms:
               ^^^
  File "/home/vince/batmon-ha2/bmslib/models/BLE_BMS_wrap.py", line 87, in __aenter__
    await self.connect()
  File "/home/vince/batmon-ha2/bmslib/models/BLE_BMS_wrap.py", line 98, in connect
    ble_device = await BLEDeviceResolver.resolve(self.address, adapter=self.adapter or None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vince/batmon-ha2/bmslib/models/BLE_BMS_wrap.py", line 28, in resolve
    scanner = await get_shared_scanner(adapter)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vince/batmon-ha2/bmslib/scan.py", line 33, in get_shared_scanner
    await sc.start()
  File "/home/vince/batmon-ha2/venv/lib/python3.13/site-packages/bleak/__init__.py", line 153, in start
    await self._backend.start()
  File "/home/vince/batmon-ha2/venv/lib/python3.13/site-packages/bleak/backends/bluezdbus/scanner.py", line 137, in star
t
    self._stop = await manager.active_scan(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/home/vince/batmon-ha2/venv/lib/python3.13/site-packages/bleak/backends/bluezdbus/manager.py", line 442, in acti
ve_scan
    assert_reply(reply)
    ~~~~~~~~~~~~^^^^^^^
  File "/home/vince/batmon-ha2/venv/lib/python3.13/site-packages/bleak/backends/bluezdbus/utils.py", line 27, in assert_
reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress
13:50:25 ERROR [sampling] <bmslib.models.BLE_BMS_wrap.BMS object at 0x778f6c7b2ba0> device not found, retry in 11 second
s (BleakDeviceNotFoundError)
13:50:45 ERROR [sampling] <bmslib.models.BLE_BMS_wrap.BMS object at 0x778f6c7b2ba0> device not found, retry in 25 second
s (BleakDeviceNotFoundError)
13:51:22 ERROR [sampling] <bmslib.models.BLE_BMS_wrap.BMS object at 0x778f6c7b2ba0> device not found, retry in 129 secon
ds (BleakDeviceNotFoundError)
13:51:36 INFO [main] Disconnecting <bmslib.models.BLE_BMS_wrap.BMS object at 0x778f6c7b2ba0>
```


Battery is a WattCycle battery, and my options.json (partially redacted) is...

```
{
  "devices": [
    {
      "address": "C0:D6:3C:58:27:87",
      "type": "tdt",
      "alias": "battery1",
      "adapter": "hci0",
      "debug": "true"
    }
  ],
  "mqtt_broker": "redacted",
  "mqtt_user": "redacted",
  "mqtt_password": "redacted",
  "concurrent_sampling": false,
  "keep_alive": true,
  "sample_period": 5.0,
  "publish_period": 5.0,
  "invert_current": false,
  "expire_values_after": 20,
  "verbose_log": true,
  "watchdog": false
 }
```

So...  any ideas? Did I mess something up? Obviously only starting with one battery even though I have four; no need to complicate things.

**Comment by fl4p** [comment]
I still don't fully understand the "OperationInProgress" error, its probably related to ble scanning, that can only be activated once. It also happens during connect, as bleak resolves the device address. I tried to fix it with shared scanners and locks to prevent mutual execution but it didn't fix the problem.

Try to downgrade to 1.90, this appears to be the most stable version.

**Comment by TheKorn2** [comment]
Well, got some more time.  Put up a temporary copy of ubuntu server (no GNOME) and that made most of the inprogress stuff disappear. Code still doesn't want to connect, so I'm giving up at this point. Thanks anyway.

**Comment by TheKorn2** [comment]
@fl4p Just wanted to do a postmortem on this with some observations. Maybe it'll be helpful/useful, maybe not, but figured I'd pass them along nonetheless.

First off, _**thankyouthankyouthankyou**_ for writing this software! When it's working, it's a fire-and-forget dream!  

(Equipment to be monitored is 4x tdt, and 1x victron smart shunt)

Originally I was testing this on a regular full-fat ubuntu build on a spare PC, and I couldn't get anywhere with that. (This is what generated this issue originally.) My gut feeling is that something with GNOME's bluetooth handler was mucking up the works entirely. So you might want to add a note (somewhere) about installing on a full ubuntu build being no bueno.

Next I tried a server build of ubuntu, which doesn't have a GUI but still includes bluez. Got a lot farther with that, but still wasn't entirely good. If I configured the system to try and read just the TDTs, I could get 3 out of 4 to come up reliably. Which exact TDT didn't want to talk rotated depending on the phase of the moon and the second hand on the pope's wristwatch, but once those three came up they'd be rock solid. If I configured for the tdts with the victron, it'd initially fire up OK but go unresponsive after about five minutes every time. (I could kill it and restart for another five minutes of data.) If I configured just the victron it'd run for a week solid. Moving the bluetooth unit didn't change anything, using an external bluetooth dongle didn't change anything, and using tdt on the built in and victron on the external (or vice-versa) didn't change anything.

Finally for another project I bought a raspberry pi (running Trixie/13.1) and decided to try again for giggles. All my problems disappeared like a fart in the wind! I can configure all four tdts + victron and it runs and runs until _**I**_ kill it for one unrelated linux housekeeping reason or another!

So I don't know what's going on with the ubuntu bluez config, but that certainly was the cause of almost all my problems. Once I switched to raspbian, it's been smooth sailing ever since!
